db.host=crossover.proxy.rlwy.net
db.port=21559
db.name=railway
db.user=postgres
db.password=ARLiAEBjAZqFnfqcukaYbGhklLHHBtLy
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
db.pool.maxLifetime=1800000